AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

Globals:
    Function:
        Timeout: 3

Resources:
    SiteNameFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: siteName/
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt SiteNameFunctionRole.Arn
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                rootUrlAccess:
                    Type: Api
                    Properties:
                        Path: /
                        Method: get
                contentsUrlAccess:
                    Type: Api
                    Properties:
                        Path: /contents/{filename+}
                        Method: get

    SiteNameFunctionRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: "sts:AssumeRole"
          Policies:
            - 
              PolicyName: "SiteNameFunctionPolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action: "s3:PutObject"
                    Resource: "arn:aws:s3:::sitename20190112/*"
                  -
                    Effect: "Allow"
                    Action: "s3:GetObject"
                    Resource: "arn:aws:s3:::sitename20190112/*"
                  -
                    Effect: "Allow"
                    Action:
                      - "logs:CreateLogStream"
                      - "logs:CreateLogGroup"
                      - "logs:PutLogEvents"
                    Resource: "*"

Outputs:
    SiteNameApi:
      Description: "API Gateway endpoint URL for Prod stage for Spa Sample function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contents/{filename+}"

    SiteNameFunction:
      Description: "Site Name Lambda Function ARN"
      Value: !GetAtt SiteNameFunction.Arn

    SiteNameFunctionIamRole:
      Description: "Implicit IAM Role created for Site Name function"
      Value: !GetAtt SiteNameFunctionRole.Arn

